name: "Update submodule"
on:
  repository_dispatch:
    types: [RUN_WORKFLOW_DISPATCH]
      
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: Update Submodule
        run: |
          git submodule update --remote

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[배포] Submodule sync"
          branch: main
          commit_user_name: sync-bot 🤖
          commit_user_email: kmj4138@gmail.com
          commit_author: importer-bot 🤖 <kmj4138@gmail.com>
 